//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatsUrSay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Group
    {
        public int id { get; set; }
        public int activity_id { get; set; }
        public int group_id { get; set; }
    
        public  Activity Activity { get; set; }
        public  Group Group { get; set; }
    }
}
